### ISSUE TITLE
Ran install script on Kali 2020.3 and now Firefox doesn't work

### ISSUE THREAD

**Issue by spencer5cent** [ShivamRai2003/Reconky-Automated_Bash_Script#1]
Hi, I just ran the install script and started using this tool.  It hangs after saying "Enumeration has finished" and the folders waybackurls and scans is always empty.  Also, firefox gave me an issue saying it had been updated and has to be restarted, and now web pages don't load anymore.  I can fix it/reinstall kali so it's not too big a deal but, do you know what could have caused this?  Thanks.

**Comment by ShivamRai2003** [comment]
Hi, Did you got any error after running install.sh ? make sure to run everything as root. also this tool tested on the kali linux 2021.2 live image. and this script is running perfectly and Firefox is working as well.

**Comment by spencer5cent** [comment]
No, there were no errors.  And actually I was wrong about it hanging after the Enumeration, it just took a while.  So the script seems to running fine but I'm not sure what happened with my web browser.

**Comment by ShivamRai2003** [comment]
Reinstall the Firefox or install any other browser  :)
Make sure to message me on twitter if you got any error or problem. Happy hacking !
